name: Python application CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov playwright
        playwright install
        playwright install-deps
    - name: Run unit and integration tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      run: |
        pytest tests/unit tests/integration --cov=./ --cov-report=xml
    - name: Run E2E tests
      run: |
        python app.py &  # Iniciar servidor en segundo plano
        sleep 5  # Esperar que el servidor inicie
        pytest tests/e2e
        kill $!  # Detener servidor
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3